apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubenetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/haint/udacity-techtrends.git
    targetRevision: HEAD
    helm:
      values:
        - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
